language: python

python:
  - "3.5"
  - "3.5-dev"  
  - "3.6"
  - "3.6-dev"  

install:
  - pip install -r requirements.txt

script: 
  - pytest

env:
  - BOT_ID="e403ea1c8dd6db80f7583c32cf" BOT_TYPE="groupme" LEAGUE_ID="356572479369535488"